/home/user/anaconda3/envs/abides/lib/python3.7/site-packages/skimage/io/manage_plugins.py:23: UserWarning: Your installed pillow version is < 8.1.2. Several security issues (CVE-2021-27921, CVE-2021-25290, CVE-2021-25291, CVE-2021-25293, and more) have been fixed in pillow 8.1.2 or higher. We recommend to upgrade this library.
  from .collection import imread_collection_wrapper
#PTs: 1; Momentum: 1; Timestep: 60S
Traceback (most recent call last):
  File "recovery_tests.py", line 63, in <module>
    transitions = {id: pd.read_csv(f'data/transitions_{id}.csv', header=None).values for id in ids}
  File "recovery_tests.py", line 63, in <dictcomp>
    transitions = {id: pd.read_csv(f'data/transitions_{id}.csv', header=None).values for id in ids}
  File "/home/user/anaconda3/envs/abides/lib/python3.7/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/user/anaconda3/envs/abides/lib/python3.7/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/user/anaconda3/envs/abides/lib/python3.7/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/user/anaconda3/envs/abides/lib/python3.7/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/user/anaconda3/envs/abides/lib/python3.7/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/home/user/anaconda3/envs/abides/lib/python3.7/site-packages/pandas/io/parsers.py", line 1368, in _open_handles
    storage_options=kwds.get("storage_options", None),
  File "/home/user/anaconda3/envs/abides/lib/python3.7/site-packages/pandas/io/common.py", line 647, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'data/transitions_MM.csv'
